# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Innovation through computer science enlightens the day, and guards the night.
email: isaackarwailow@gmail.com
description: >
  This blog reflects my pursuit of the things I have learnt throughout the years in my career. 
  I started out with a Bachelor of Arts in English and attained a Masters in Information Technology with a major in Data Analytics.

  Througout my 1.7 years experience as an Analyst Data Engineer, I have pieced together my pitch for the kind of value I bring to a company:
  I am passionate about new ideas/ ways of working. I am particularly interested in innovative spaces in Penetration Testing and Data Science.

  In my day job, I most enjoy utilizing and documenting innovative pieces of code to help my team 
  be more productive.

  I also happen to enjoy reading about OffSec topics to further develop my security awareness. I have communicated to stakeholders on
  around 20 different metrics for FinCrime, but am looking for more challenges in the innovative space.

  I enjoy finding solid and sustainable hygene for adopting a great defensive appetite involving security awareness. I believe that
  is a culture and awareness that all teams should have. I aspire to be someone who delivers value in the security space using the latest
  techniques and methodologies

   \n

baseurl: "https://isaackarwailow.github.io/blog.html" # the subpath of your site, e.g. /blog
url: "https://isaackarwailow.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "https://twitter.com/rogomerlin"
github_username: "rogomerlin"
collections:
  authors:
    output: true
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
